### ISSUE TITLE
Cannot be executed [FATAL]  

### ISSUE THREAD

**Issue by John-H-Smith** [emilkrebs/Generator-Discord#9]
I just tried using the generator, but it don't find the generator.
```
$ yo discord
Error discord 

You don't seem to have a generator with the name “discord” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-discord.

To see all your installed generators run yo --generators. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

Here's the output of my installed modules:
```
$ npm list -g
/home/user/.nvm/versions/node/v18.8.0/lib
├── @nestjs/cli@9.4.0
├── corepack@0.13.0
├── generator-discord@1.1.7
├── nodemon@2.0.21
├── npm@8.18.0
└── yo@4.3.1
```
Generator is found from yeoman too:
```
$ yo --generators
Available Generators:

  discord
    src
```
Installed it like in the [README](https://github.com/emilkrebs/Generator-Discord/blob/main/README.md).

**Comment by emilkrebs** [comment]
Thats weird, have you tried running `yo discord ` in a fresh terminal session?

**Comment by John-H-Smith** [comment]
Yep, I tried it on 2 seperate computers, one on windows and one on linux.

**Comment by emilkrebs** [comment]
Okay, Its a problem with version `1.1.7` try installing `1.1.5` using `npm i -g generator-discord@1.1.5`. Thank you for opening this issue, I will work on fixing this problem.

**Comment by emilkrebs** [comment]
![image](https://github.com/emilkrebs/Generator-Discord/assets/68400102/f9da0975-57a3-4c25-9d52-506aec130595)

how haven't I noticed this

**Comment by emilkrebs** [comment]
Fixed the build Issue, and updated all dependencies. I hope it works for you as well.
